import { useEffect, useRef, useState } from "react";
import { ActivityIndicator, Alert, Animated, Easing, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { sendPaperPlane } from "../api/bored";
import { useAuth } from "../context/AuthContext";
import { useTheme } from "../context/ThemeContext";
import { getWallet } from "../api/wallet";

export default function SendPaperPlaneScreen() {
  const { user, token } = useAuth(); const { colors } = useTheme();
  const [message, setMessage] = useState(""); const [sending, setSending] = useState(false); const [sent, setSent] = useState(false); const [balance, setBalance] = useState<number | null>(null);
  const flight = useRef(new Animated.Value(0)).current;
  useEffect(() => { if (token) getWallet(token).then((wallet) => setBalance(wallet.balance)).catch(() => undefined); }, [token]);
  useEffect(() => { if (!sent) return; const animation = Animated.loop(Animated.sequence([Animated.timing(flight, { toValue: 1, duration: 1700, easing: Easing.inOut(Easing.quad), useNativeDriver: true }), Animated.timing(flight, { toValue: 0, duration: 1, useNativeDriver: true })])); animation.start(); return () => animation.stop(); }, [flight, sent]);
  async function send() { const note = message.trim(); if (!token || sending) return; if (!note) return Alert.alert("Write a note", "Add a short message before sending your Paper Plane."); try { setSending(true); const result = await sendPaperPlane(token, note); setBalance(result.wallet.balance); setSent(true); } catch (error: any) { Alert.alert("Unable to send", error?.response?.data?.message ?? "Please try again in a moment."); } finally { setSending(false); } }
  if (!user) return <View style={[styles.loading, { backgroundColor: colors.canvas }]}><ActivityIndicator color={colors.teal} size="large" /></View>;
  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.canvas }]}><View style={styles.container}><TouchableOpacity onPress={() => router.back()}><Text style={[styles.back, { color: colors.teal }]}>← Back to desk</Text></TouchableOpacity><Text style={[styles.brand, { color: colors.teal }]}>PAPER PLANE</Text>{balance !== null && <Text style={[styles.wallet, { color: colors.muted }]}>Salary wallet · {balance.toLocaleString("en-IN")} Paisa</Text>}<View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{sent ? <><View style={styles.flightLane}><Animated.Text style={[styles.plane, { color: colors.teal, transform: [{ translateX: flight.interpolate({ inputRange: [0, 1], outputRange: [-110, 220] }) }, { rotate: "-18deg" }] }]}>✈</Animated.Text></View><Text style={[styles.title, { color: colors.text }]}>Your Paper Plane is in the sky.</Text><Text style={[styles.copy, { color: colors.muted }]}>It will land on one available desk and remain there for up to 24 hours.</Text><TouchableOpacity style={[styles.button, { backgroundColor: colors.teal }]} onPress={() => { setMessage(""); setSent(false); }}><Text style={styles.buttonText}>Send another plane</Text></TouchableOpacity></> : <><Text style={[styles.title, { color: colors.text }]}>Send a Paper Plane</Text><Text style={[styles.copy, { color: colors.muted }]}>Write a short invitation. It will land on one active Breakroom desk.</Text><TextInput value={message} onChangeText={setMessage} maxLength={160} multiline placeholder="Coffee break? Tell me one good thing from your day." placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, borderColor: colors.border, backgroundColor: colors.surfaceSoft }]} /><View style={styles.details}><Text style={[styles.counter, { color: colors.muted }]}>{message.length}/160</Text><Text style={[styles.cost, { color: colors.teal }]}>10 Paisa · 24 hours</Text></View><TouchableOpacity disabled={sending} style={[styles.button, { backgroundColor: colors.teal, opacity: sending ? .6 : 1 }]} onPress={send}><Text style={styles.buttonText}>{sending ? "Sending…" : "Send Paper Plane"}</Text></TouchableOpacity></>}</View></View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, container: { flex: 1, padding: 22, justifyContent: "center" }, loading: { flex: 1, alignItems: "center", justifyContent: "center" }, back: { position: "absolute", top: 20, left: 22, fontWeight: "800" }, brand: { fontSize: 10, fontWeight: "900", letterSpacing: 1.4, textAlign: "center" }, wallet: { textAlign: "center", fontSize: 12, marginTop: 8 }, card: { borderRadius: 20, borderWidth: 1, padding: 24, marginTop: 22 }, title: { fontSize: 27, fontWeight: "900" }, copy: { fontSize: 15, lineHeight: 22, marginTop: 10 }, input: { minHeight: 112, borderWidth: 1, borderRadius: 12, marginTop: 20, padding: 12, textAlignVertical: "top", fontSize: 14 }, details: { flexDirection: "row", justifyContent: "space-between", marginTop: 7 }, counter: { fontSize: 11, fontWeight: "700" }, cost: { fontSize: 11, fontWeight: "800" }, button: { minHeight: 52, borderRadius: 13, alignItems: "center", justifyContent: "center", marginTop: 24 }, buttonText: { color: "#FFF", fontSize: 15, fontWeight: "900" }, flightLane: { height: 40, overflow: "hidden", marginBottom: 12 }, plane: { fontSize: 29 } });
