import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { CultureOverview, getCulture, joinCoffee, leaveCoffee, saveInterests, sendKudos, submitChallenge, submitPrompt } from "../api/culture";
import { getWorkCircle, CircleConnection } from "../api/work-circle";
import { useAuth } from "../context/AuthContext";
import { useTheme } from "../context/ThemeContext";

export default function CultureHub() {
  const { token } = useAuth(); const { colors } = useTheme();
  const [data, setData] = useState<CultureOverview | null>(null); const [circle, setCircle] = useState<CircleConnection[]>([]); const [loading, setLoading] = useState(true); const [promptText, setPromptText] = useState(""); const [challengeText, setChallengeText] = useState(""); const [kudosText, setKudosText] = useState(""); const [recipient, setRecipient] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!token) return; try { const [culture, workCircle] = await Promise.all([getCulture(token), getWorkCircle(token)]); setData(culture); setCircle(workCircle.connections); setPromptText(culture.prompt.mine ?? ""); } catch { Alert.alert("Culture Hub", "We could not load today’s breakroom activities."); } finally { setLoading(false); } }, [token]);
  useEffect(() => { load(); }, [load]);
  async function action(run: () => Promise<unknown>, success?: string) { try { setBusy(true); await run(); if (success) Alert.alert("Culture Hub", success); await load(); } catch (error: any) { Alert.alert("Culture Hub", error?.response?.data?.message ?? "Please try again."); } finally { setBusy(false); } }
  if (loading || !data) return <SafeAreaView style={[styles.safe, { backgroundColor: colors.canvas }]}><ActivityIndicator style={styles.loader} color={colors.teal} /></SafeAreaView>;
  const toggleInterest = (interest: string) => { const next = data.myInterests.includes(interest) ? data.myInterests.filter((item) => item !== interest) : [...data.myInterests, interest]; if (next.length > 5) return Alert.alert("Choose up to five", "Keep your interests focused so pairings stay relevant."); action(() => saveInterests(token!, next)); };
  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.canvas }]}><ScrollView contentContainerStyle={styles.content}>
    <Text style={[styles.eyebrow, { color: colors.teal }]}>BREAKROOM CULTURE</Text><Text style={[styles.title, { color: colors.navy }]}>Make your break count.</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Short, opt-in moments for people who want more than scrolling.</Text>
    <View style={[styles.hero, { backgroundColor: colors.hero }]}><Text style={[styles.heroLabel, { color: colors.mint }]}>COFFEE PAIRING</Text><Text style={styles.heroTitle}>{data.coffeeTopic ? `Waiting to discuss ${data.coffeeTopic}` : "Find a 10-minute coffee chat"}</Text><Text style={styles.heroText}>Choose a topic. When someone picks the same one, you are paired in a private chat.</Text>{data.coffeeTopic ? <TouchableOpacity disabled={busy} onPress={() => action(() => leaveCoffee(token!), "You left the coffee queue.")} style={[styles.heroButton, { backgroundColor: colors.surface }]}><Text style={[styles.heroButtonText, { color: colors.navy }]}>Leave queue</Text></TouchableOpacity> : <View style={styles.topicRow}>{["Any topic", ...data.myInterests.slice(0, 3)].map((topic) => <TouchableOpacity disabled={busy} key={topic} onPress={() => action(async () => { const result = await joinCoffee(token!, topic); if (result.matched && result.chat) router.push({ pathname: "/chat/[chatId]", params: { chatId: result.chat.id, direct: "1" } }); }, "You are in the coffee queue.")} style={[styles.topic, { backgroundColor: colors.mint }]}><Text style={[styles.topicText, { color: colors.onAccent }]}>{topic}</Text></TouchableOpacity>)}</View>}</View>
    <Section title="Daily Desk Prompt" colors={colors}><Text style={[styles.question, { color: colors.text }]}>{data.prompt.text}</Text><TextInput value={promptText} onChangeText={setPromptText} maxLength={240} multiline placeholder="Share a thoughtful one-line answer" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, borderColor: colors.border }]} /><Button colors={colors} disabled={busy || !promptText.trim()} label={data.prompt.mine ? "Update answer" : "Share answer"} onPress={() => action(() => submitPrompt(token!, promptText.trim()))} />{data.prompt.responses.slice(0, 4).map((item) => <Response key={item.id} colors={colors} name={item.author.anonymousUsername} text={item.text} />)}</Section>
    <Section title="Breakroom Challenge" colors={colors}><Text style={[styles.question, { color: colors.text }]}>{data.challenge.text}</Text><TextInput value={challengeText} onChangeText={setChallengeText} maxLength={160} multiline placeholder="Your answer" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, borderColor: colors.border }]} /><Button colors={colors} disabled={busy || !challengeText.trim()} label="Join challenge" onPress={() => action(() => submitChallenge(token!, challengeText.trim()))} />{data.challenge.responses.slice(0, 4).map((item) => <Response key={item.id} colors={colors} name={item.author.anonymousUsername} text={item.text} />)}</Section>
    <Section title="Your interests" colors={colors}><Text style={[styles.help, { color: colors.muted }]}>Used to make Coffee Pairing more relevant. Choose up to five.</Text><View style={styles.chips}>{data.interests.map((interest) => <TouchableOpacity key={interest} onPress={() => toggleInterest(interest)} style={[styles.chip, { borderColor: colors.border }, data.myInterests.includes(interest) && { backgroundColor: colors.teal, borderColor: colors.teal }]}><Text style={[styles.chipText, { color: colors.text }, data.myInterests.includes(interest) && { color: "#FFF" }]}>{interest}</Text></TouchableOpacity>)}</View></Section>
    <Section title="Appreciation Wall" colors={colors}>{circle.length ? <><Text style={[styles.help, { color: colors.muted }]}>Send a short, public thank-you to someone in your Work Circle.</Text><View style={styles.chips}>{circle.map((item) => <TouchableOpacity key={item.id} onPress={() => setRecipient(item.member.id)} style={[styles.chip, { borderColor: colors.border }, recipient === item.member.id && { backgroundColor: colors.violet, borderColor: colors.violet }]}><Text style={[styles.chipText, { color: colors.text }, recipient === item.member.id && { color: "#FFF" }]}>{item.member.anonymousUsername}</Text></TouchableOpacity>)}</View><TextInput value={kudosText} onChangeText={setKudosText} maxLength={240} placeholder="Thank them for something specific" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, borderColor: colors.border }]} /><Button colors={colors} disabled={busy || !recipient || !kudosText.trim()} label="Send appreciation" onPress={() => action(() => sendKudos(token!, recipient!, kudosText.trim()), "Your appreciation is on the wall.")} /></> : <Text style={[styles.help, { color: colors.muted }]}>Build your Work Circle after a match or Paper Plane chat to send appreciation.</Text>}{data.kudos.slice(0, 5).map((item) => <Response key={item.id} colors={colors} name={`${item.sender.anonymousUsername} appreciated ${item.recipient.anonymousUsername}`} text={item.message} />)}</Section>
  </ScrollView></SafeAreaView>;
}
function Section({ title, colors, children }: any) { return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.sectionTitle, { color: colors.navy }]}>{title}</Text>{children}</View>; }
function Response({ name, text, colors }: { name: string; text: string; colors: any }) { return <View style={[styles.response, { backgroundColor: colors.surfaceSoft }]}><Text style={[styles.responseName, { color: colors.teal }]}>{name}</Text><Text style={[styles.responseText, { color: colors.text }]}>{text}</Text></View>; }
function Button({ label, onPress, disabled, colors }: any) { return <TouchableOpacity disabled={disabled} onPress={onPress} style={[styles.button, { backgroundColor: colors.navy }, disabled && styles.disabled]}><Text style={styles.buttonText}>{label}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, loader: { marginTop: 100 }, content: { padding: 22, paddingBottom: 36 }, eyebrow: { fontWeight: "900", letterSpacing: 1.4, fontSize: 11 }, title: { fontWeight: "900", fontSize: 30, marginTop: 9 }, subtitle: { lineHeight: 21, marginTop: 7 }, hero: { borderRadius: 22, padding: 22, marginTop: 22 }, heroLabel: { fontSize: 10, fontWeight: "900", letterSpacing: 1.3 }, heroTitle: { color: "#FFF", fontSize: 21, lineHeight: 28, fontWeight: "900", marginTop: 11 }, heroText: { color: "#D8E1FF", fontSize: 14, lineHeight: 20, marginTop: 8 }, heroButton: { borderRadius: 11, padding: 13, alignItems: "center", marginTop: 18 }, heroButtonText: { fontWeight: "900" }, topicRow: { flexDirection: "row", gap: 8, flexWrap: "wrap", marginTop: 17 }, topic: { paddingVertical: 10, paddingHorizontal: 11, borderRadius: 10 }, topicText: { fontSize: 12, fontWeight: "900" }, card: { padding: 18, borderWidth: 1, borderRadius: 18, marginTop: 14 }, sectionTitle: { fontSize: 17, fontWeight: "900" }, question: { fontSize: 15, fontWeight: "700", lineHeight: 22, marginTop: 12 }, help: { fontSize: 13, lineHeight: 19, marginTop: 9 }, input: { borderWidth: 1, borderRadius: 11, minHeight: 65, padding: 11, textAlignVertical: "top", marginTop: 13 }, button: { borderRadius: 11, padding: 12, alignItems: "center", marginTop: 10 }, buttonText: { color: "#FFF", fontWeight: "900" }, disabled: { opacity: .45 }, response: { marginTop: 10, padding: 11, borderRadius: 11 }, responseName: { fontWeight: "900", fontSize: 12 }, responseText: { fontSize: 13, lineHeight: 19, marginTop: 3 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 12 }, chip: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 8 }, chipText: { fontSize: 12, fontWeight: "800" } });
