import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, FlatList, RefreshControl, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { addStickyComment, createStickyNote, deleteStickyNote, DeskStickyNote, getStickyNotes, replyToStickyComment, toggleStickyApplaud } from "../api/stickies";
import { blockUser, reportContent } from "../api/safety";
import { useAuth } from "../context/AuthContext";
import { useTheme } from "../context/ThemeContext";

export default function DeskNotesScreen() {
  const { token, user } = useAuth();
  const { colors } = useTheme();
  const [notes, setNotes] = useState<DeskStickyNote[]>([]);
  const [text, setText] = useState("");
  const [comments, setComments] = useState<Record<string, string>>({});
  const [replies, setReplies] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [publishing, setPublishing] = useState(false);

  const load = useCallback(async () => { if (!token) return; try { setNotes(await getStickyNotes(token)); } catch { Alert.alert("Desk Notes unavailable", "Please try again shortly."); } finally { setLoading(false); } }, [token]);
  useEffect(() => { load(); }, [load]);

  async function publish() { if (!token || !text.trim() || publishing) return; try { setPublishing(true); const note = await createStickyNote(token, text.trim()); setNotes((current) => [note, ...current]); setText(""); } catch (error: any) { Alert.alert("Couldn’t pin note", error?.response?.data?.message ?? "Please try again."); } finally { setPublishing(false); } }
  async function applaud(noteId: string) { if (!token) return; try { const result = await toggleStickyApplaud(token, noteId); setNotes((current) => current.map((note) => note.id === noteId ? { ...note, applaudedByMe: result.applauded, _count: { applauds: result.applauds } } : note)); } catch { Alert.alert("Couldn’t applaud", "Please try again."); } }
  async function comment(noteId: string) { const value = comments[noteId]?.trim(); if (!token || !value) return; try { const newComment = await addStickyComment(token, noteId, value); setNotes((current) => current.map((note) => note.id === noteId ? { ...note, comments: [...note.comments, newComment] } : note)); setComments((current) => ({ ...current, [noteId]: "" })); } catch (error: any) { Alert.alert("Couldn’t add comment", error?.response?.data?.message ?? "Please try again."); } }
  async function reply(noteId: string, commentId: string) { const value = replies[commentId]?.trim(); if (!token || !value) return; try { const updated = await replyToStickyComment(token, noteId, commentId, value); setNotes((current) => current.map((note) => note.id === noteId ? { ...note, comments: note.comments.map((entry) => entry.id === commentId ? updated : entry) } : note)); setReplies((current) => ({ ...current, [commentId]: "" })); } catch (error: any) { Alert.alert("Couldn’t reply", error?.response?.data?.message ?? "Please try again."); } }
  function removeNote(noteId: string) { if (!token) return; Alert.alert("Delete Desk Note?", "This removes the note, its applause, and all its comments for everyone.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: async () => { try { await deleteStickyNote(token, noteId); setNotes((current) => current.filter((note) => note.id !== noteId)); } catch (error: any) { Alert.alert("Couldn’t delete note", error?.response?.data?.message ?? "Please try again."); } } }]); }
  async function report(targetType: "STICKY_NOTE" | "STICKY_COMMENT", targetId: string) { if (!token) return; try { await reportContent(token, targetType, targetId, "Inappropriate Desk Note content"); Alert.alert("Report received", "Thank you. A moderator will review it."); } catch { Alert.alert("Couldn’t report", "Please try again."); } }
  async function block(authorId: string) { if (!token) return; try { await blockUser(token, authorId); setNotes((current) => current.filter((note) => note.author.id !== authorId)); } catch { Alert.alert("Couldn’t block member", "Please try again."); } }

  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.canvas }]}><FlatList data={notes} keyExtractor={(item) => item.id} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => { setLoading(true); load(); }} tintColor={colors.teal} />} contentContainerStyle={styles.list}
    ListHeaderComponent={<View><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><Text style={[styles.back, { color: colors.teal }]}>← Back</Text></TouchableOpacity><Text style={[styles.brand, { color: colors.teal }]}>DESK NOTES</Text></View><Text style={[styles.title, { color: colors.navy }]}>A little note from your desk.</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Share a short public thought with the Breakroom. Keep it kind and work-safe.</Text><View style={[styles.composer, { backgroundColor: colors.surface, borderColor: colors.border }]}><TextInput value={text} onChangeText={setText} maxLength={160} multiline placeholder="What are you thinking about?" placeholderTextColor={colors.muted} style={[styles.composerInput, { color: colors.text }]} /><View style={styles.composerBottom}><Text style={[styles.count, { color: colors.muted }]}>{text.length}/160</Text><TouchableOpacity disabled={publishing || !text.trim()} onPress={publish} style={[styles.pinButton, { backgroundColor: colors.navy }, (!text.trim() || publishing) && styles.disabled]}><Text style={styles.pinText}>{publishing ? "Pinning…" : "Pin note"}</Text></TouchableOpacity></View></View><Text style={[styles.section, { color: colors.text }]}>Desk ticker</Text></View>}
    ListEmptyComponent={loading ? <ActivityIndicator color={colors.teal} style={styles.loader} /> : <Text style={[styles.empty, { color: colors.muted }]}>No Desk Notes yet. Add the first one.</Text>}
    renderItem={({ item }) => <DeskNoteCard note={item} isOwner={item.author.id === user?.id} colors={colors} commentDraft={comments[item.id] ?? ""} onChangeComment={(value) => setComments((current) => ({ ...current, [item.id]: value }))} onComment={() => comment(item.id)} replyDrafts={replies} onChangeReply={(commentId, value) => setReplies((current) => ({ ...current, [commentId]: value }))} onReply={reply} onApplaud={() => applaud(item.id)} onDelete={() => removeNote(item.id)} onReport={report} onBlock={block} />}
  /></SafeAreaView>;
}

function DeskNoteCard({ note, isOwner, colors, commentDraft, onChangeComment, onComment, replyDrafts, onChangeReply, onReply, onApplaud, onDelete, onReport, onBlock }: { note: DeskStickyNote; isOwner: boolean; colors: any; commentDraft: string; onChangeComment: (value: string) => void; onComment: () => void; replyDrafts: Record<string, string>; onChangeReply: (commentId: string, value: string) => void; onReply: (noteId: string, commentId: string) => void; onApplaud: () => void; onDelete: () => void; onReport: (type: "STICKY_NOTE" | "STICKY_COMMENT", id: string) => void; onBlock: (authorId: string) => void }) {
  return <View style={[styles.note, { backgroundColor: colors.amberSoft, borderColor: colors.border }]}><View style={styles.noteTop}><TouchableOpacity onPress={() => router.push(`/profile/${note.author.id}` as any)}><Text style={[styles.author, { color: colors.violet }]}>{note.author.anonymousUsername}</Text></TouchableOpacity>{isOwner ? <TouchableOpacity onPress={onDelete}><Text style={[styles.report, { color: colors.danger }]}>Delete</Text></TouchableOpacity> : <TouchableOpacity onPress={() => onReport("STICKY_NOTE", note.id)}><Text style={[styles.report, { color: colors.danger }]}>Report</Text></TouchableOpacity>}</View><Text style={[styles.noteText, { color: colors.text }]}>{note.text}</Text><View style={styles.reactions}><TouchableOpacity onPress={onApplaud}><Text style={[styles.applaud, { color: note.applaudedByMe ? colors.teal : colors.muted }]}>{note.applaudedByMe ? "Applauded" : "Applaud"} · {note._count.applauds}</Text></TouchableOpacity>{!isOwner && <TouchableOpacity onPress={() => onBlock(note.author.id)}><Text style={[styles.block, { color: colors.muted }]}>Block</Text></TouchableOpacity>}</View>{note.comments.map((entry) => <View key={entry.id} style={[styles.comment, { backgroundColor: colors.surface }]}><View style={styles.commentTop}><TouchableOpacity onPress={() => router.push(`/profile/${entry.author.id}` as any)}><Text style={[styles.commentAuthor, { color: colors.violet }]}>{entry.author.anonymousUsername}</Text></TouchableOpacity><TouchableOpacity onPress={() => onReport("STICKY_COMMENT", entry.id)}><Text style={[styles.commentReport, { color: colors.danger }]}>Report</Text></TouchableOpacity></View><Text style={[styles.commentText, { color: colors.text }]}>{entry.text}</Text>{entry.authorReply ? <View style={[styles.authorReply, { borderColor: colors.border }]}><Text style={[styles.replyLabel, { color: colors.teal }]}>Your reply</Text><Text style={[styles.replyText, { color: colors.text }]}>{entry.authorReply}</Text></View> : isOwner ? <View style={[styles.replyComposer, { borderColor: colors.border }]}><TextInput value={replyDrafts[entry.id] ?? ""} onChangeText={(value) => onChangeReply(entry.id, value)} maxLength={240} placeholder="Reply with a quick thank-you" placeholderTextColor={colors.muted} style={[styles.replyInput, { color: colors.text }]} /><TouchableOpacity onPress={() => onReply(note.id, entry.id)}><Text style={[styles.send, { color: colors.teal }]}>Reply</Text></TouchableOpacity></View> : null}</View>)}<View style={[styles.commentComposer, { borderColor: colors.border }]}><TextInput value={commentDraft} onChangeText={onChangeComment} maxLength={300} onSubmitEditing={onComment} placeholder="Add a comment" placeholderTextColor={colors.muted} style={[styles.commentInput, { color: colors.text }]} /><TouchableOpacity onPress={onComment}><Text style={[styles.send, { color: colors.teal }]}>Send</Text></TouchableOpacity></View></View>;
}

const styles = StyleSheet.create({
  safe: { flex: 1 }, list: { padding: 18, paddingBottom: 38 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, back: { fontWeight: "900" }, brand: { fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, title: { fontSize: 28, fontWeight: "900", marginTop: 25 }, subtitle: { fontSize: 14, lineHeight: 20, marginTop: 7 }, composer: { borderWidth: 1, borderRadius: 18, padding: 15, marginTop: 19 }, composerInput: { minHeight: 70, fontSize: 15, lineHeight: 21, textAlignVertical: "top" }, composerBottom: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 8 }, count: { fontSize: 11, fontWeight: "800" }, pinButton: { minHeight: 39, paddingHorizontal: 14, alignItems: "center", justifyContent: "center", borderRadius: 10 }, pinText: { color: "#FFF", fontSize: 12, fontWeight: "900" }, disabled: { opacity: .55 }, section: { fontSize: 16, fontWeight: "900", marginTop: 25, marginBottom: 8 }, loader: { paddingTop: 45 }, empty: { textAlign: "center", paddingTop: 45, fontSize: 14 }, note: { borderWidth: 1, borderRadius: 12, padding: 14, marginBottom: 12, transform: [{ rotate: "-0.35deg" }] }, noteTop: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, author: { fontSize: 12, fontWeight: "900" }, report: { fontSize: 11, fontWeight: "900" }, noteText: { fontSize: 15, lineHeight: 22, marginTop: 12, fontWeight: "700" }, reactions: { flexDirection: "row", gap: 20, marginTop: 15 }, applaud: { fontSize: 12, fontWeight: "900" }, block: { fontSize: 12, fontWeight: "800" }, comment: { borderRadius: 9, padding: 9, marginTop: 10 }, commentTop: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, commentAuthor: { fontSize: 11, fontWeight: "900" }, commentReport: { fontSize: 10, fontWeight: "800" }, commentText: { fontSize: 13, lineHeight: 18, marginTop: 3 }, authorReply: { borderTopWidth: 1, marginTop: 8, paddingTop: 7 }, replyLabel: { fontSize: 10, fontWeight: "900" }, replyText: { fontSize: 12, lineHeight: 17, fontWeight: "700", marginTop: 2 }, replyComposer: { flexDirection: "row", alignItems: "center", gap: 8, borderTopWidth: 1, marginTop: 8, paddingTop: 6 }, replyInput: { flex: 1, minHeight: 32, fontSize: 12 }, commentComposer: { flexDirection: "row", alignItems: "center", gap: 10, borderTopWidth: 1, marginTop: 11, paddingTop: 8 }, commentInput: { flex: 1, fontSize: 13, minHeight: 34 }, send: { fontSize: 12, fontWeight: "900" },
});
