import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { useTheme } from "../context/ThemeContext";

export default function GamesScreen() {
  const { colors } = useTheme();
  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.canvas }]}><ScrollView contentContainerStyle={styles.content}>
    <TouchableOpacity onPress={() => router.replace("/" as any)} hitSlop={10}><Text style={[styles.back, { color: colors.teal }]}>← Back to desk</Text></TouchableOpacity>
    <Text style={[styles.eyebrow, { color: colors.teal }]}>OPEN GAME TABLE</Text>
    <Text style={[styles.title, { color: colors.navy }]}>Small breaks, better reset.</Text>
    <Text style={[styles.subtitle, { color: colors.muted }]}>Choose a quick game whenever you need a few minutes away from work.</Text>
    <TouchableOpacity accessibilityRole="button" onPress={() => router.push("/tic-tac-toe" as any)} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.icon, { backgroundColor: colors.tealSoft }]}><Text style={[styles.iconText, { color: colors.teal }]}>⊞</Text></View><View style={styles.copy}><Text style={[styles.cardEyebrow, { color: colors.teal }]}>TWO PLAYERS</Text><Text style={[styles.cardTitle, { color: colors.text }]}>Tic-Tac-Toe</Text><Text style={[styles.cardText, { color: colors.muted }]}>An anonymous, quick match with someone else at Breakroom.</Text></View><Text style={[styles.arrow, { color: colors.teal }]}>→</Text></TouchableOpacity>
    <TouchableOpacity accessibilityRole="button" onPress={() => router.push("/tetris" as any)} style={[styles.card, styles.tetrisCard, { backgroundColor: colors.hero, borderColor: colors.heroAccent }]}><View style={[styles.icon, styles.tetrisIcon]}><Text style={styles.tetrisIconText}>▦</Text></View><View style={styles.copy}><Text style={styles.tetrisEyebrow}>SOLO BREAK</Text><Text style={styles.tetrisTitle}>Tetris</Text><Text style={styles.tetrisText}>Clear lines, beat your score, and return refreshed. Works offline.</Text></View><Text style={styles.tetrisArrow}>→</Text></TouchableOpacity>
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1 }, content: { padding: 22, paddingBottom: 42 }, back: { fontSize: 13, fontWeight: "900", marginBottom: 23 }, eyebrow: { fontSize: 10, letterSpacing: 1.4, fontWeight: "900" }, title: { fontSize: 30, lineHeight: 37, fontWeight: "900", marginTop: 8, maxWidth: 330 }, subtitle: { fontSize: 14, lineHeight: 21, marginTop: 9, maxWidth: 340 }, card: { borderWidth: 1, borderRadius: 20, padding: 17, marginTop: 20, flexDirection: "row", alignItems: "center", gap: 12 }, tetrisCard: { marginTop: 14 }, icon: { width: 48, height: 48, borderRadius: 15, justifyContent: "center", alignItems: "center" }, iconText: { fontSize: 24, fontWeight: "900" }, tetrisIcon: { backgroundColor: "#E9A24A" }, tetrisIconText: { color: "#342413", fontSize: 24, fontWeight: "900" }, copy: { flex: 1 }, cardEyebrow: { fontSize: 9, letterSpacing: 1.1, fontWeight: "900" }, cardTitle: { fontSize: 17, fontWeight: "900", marginTop: 3 }, cardText: { fontSize: 12, lineHeight: 17, marginTop: 4 }, arrow: { fontSize: 22, fontWeight: "900" }, tetrisEyebrow: { color: "#F2C77A", fontSize: 9, letterSpacing: 1.1, fontWeight: "900" }, tetrisTitle: { color: "#FFF", fontSize: 17, fontWeight: "900", marginTop: 3 }, tetrisText: { color: "#DDEDE9", fontSize: 12, lineHeight: 17, marginTop: 4 }, tetrisArrow: { color: "#F2C77A", fontSize: 22, fontWeight: "900" } });
