import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { getInbox, InboxConversation } from "../api/inbox";
import { useAuth } from "../context/AuthContext";
import { useTheme } from "../context/ThemeContext";

export default function InboxScreen() {
  const { token } = useAuth(); const { colors } = useTheme(); const [items, setItems] = useState<InboxConversation[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { if (!token) return; try { setItems(await getInbox(token)); } finally { setLoading(false); } }, [token]);
  useEffect(() => { load(); }, [load]);
  const time = (value: string) => new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit", month: "short", day: "numeric" }).format(new Date(value));
  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.canvas }]}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor={colors.teal} />}><Text style={[styles.eyebrow, { color: colors.teal }]}>WORK CIRCLE</Text><Text style={[styles.title, { color: colors.navy }]}>Inbox</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Private conversations with people you have mutually added.</Text>{loading ? <ActivityIndicator color={colors.teal} style={styles.loader} /> : items.length === 0 ? <View style={[styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.emptyTitle, { color: colors.text }]}>No conversations yet</Text><Text style={[styles.emptyText, { color: colors.muted }]}>Match with someone or have a Paper Plane accepted, then add each other from the chat.</Text></View> : items.map((item) => <TouchableOpacity key={item.id} onPress={() => router.push({ pathname: "/chat/[chatId]", params: { chatId: item.id, direct: "1" } })} style={[styles.row, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.violetSoft }]}><Text style={[styles.initial, { color: colors.violet }]}>{item.member.anonymousUsername[0].toUpperCase()}</Text></View><View style={styles.copy}><View style={styles.nameRow}><Text style={[styles.name, { color: colors.text }]}>{item.member.anonymousUsername}</Text><Text style={[styles.time, { color: colors.muted }]}>{time(item.updatedAt)}</Text></View><Text numberOfLines={1} style={[styles.preview, { color: colors.muted }]}>{item.latestMessage?.text ?? "You are connected — say hello."}</Text></View>{item.unreadCount > 0 && <View style={[styles.badge, { backgroundColor: colors.teal }]}><Text style={styles.badgeText}>{item.unreadCount > 9 ? "9+" : item.unreadCount}</Text></View>}</TouchableOpacity>)}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { padding: 22, paddingBottom: 38 }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "900", marginTop: 7 }, subtitle: { fontSize: 14, lineHeight: 20, marginTop: 7 }, loader: { marginTop: 60 }, empty: { borderWidth: 1, borderRadius: 18, padding: 20, marginTop: 25 }, emptyTitle: { fontWeight: "900", fontSize: 16 }, emptyText: { lineHeight: 20, fontSize: 13, marginTop: 6 }, row: { borderWidth: 1, borderRadius: 16, padding: 14, marginTop: 13, flexDirection: "row", alignItems: "center", gap: 11 }, avatar: { width: 45, height: 45, borderRadius: 14, alignItems: "center", justifyContent: "center" }, initial: { fontSize: 18, fontWeight: "900" }, copy: { flex: 1 }, nameRow: { flexDirection: "row", justifyContent: "space-between", gap: 8 }, name: { fontSize: 15, fontWeight: "900" }, time: { fontSize: 10 }, preview: { fontSize: 13, marginTop: 5 }, badge: { minWidth: 21, height: 21, borderRadius: 11, alignItems: "center", justifyContent: "center", paddingHorizontal: 5 }, badgeText: { color: "#FFF", fontSize: 10, fontWeight: "900" } });
