import { useEffect } from "react";
import { SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { useNotifications } from "../context/NotificationContext";
import { useLanguage } from "../context/LanguageContext";
import { useTheme } from "../context/ThemeContext";

export default function NotificationsScreen() {
  const { notifications, markAllRead } = useNotifications(); const { colors } = useTheme(); const { t } = useLanguage();
  useEffect(() => { void markAllRead(); }, [markAllRead]);
  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.canvas }]}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: colors.teal }]}>BREAKROOM</Text><Text style={[styles.title, { color: colors.navy }]}>{t("notifications")}</Text><Text style={[styles.subtitle, { color: colors.muted }]}>{t("notificationSubtitle")}</Text>{notifications.length === 0 ? <View style={[styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.emptyTitle, { color: colors.text }]}>{t("allCaughtUp")}</Text><Text style={[styles.emptyText, { color: colors.muted }]}>{t("notificationsEmpty")}</Text></View> : notifications.map((item) => <View key={item.id} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.dot, { backgroundColor: item.read ? colors.border : colors.teal }]} /><View style={styles.copy}><Text style={[styles.cardTitle, { color: colors.text }]}>{item.title}</Text><Text style={[styles.cardText, { color: colors.muted }]}>{item.detail}</Text></View></View>)}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { padding: 22, paddingBottom: 38 }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "900", marginTop: 7 }, subtitle: { fontSize: 14, lineHeight: 20, marginTop: 7 }, empty: { borderWidth: 1, borderRadius: 18, padding: 20, marginTop: 25 }, emptyTitle: { fontWeight: "900", fontSize: 16 }, emptyText: { lineHeight: 20, fontSize: 13, marginTop: 6 }, card: { borderWidth: 1, borderRadius: 16, padding: 15, marginTop: 13, flexDirection: "row", gap: 11 }, dot: { width: 9, height: 9, borderRadius: 5, marginTop: 5 }, copy: { flex: 1 }, cardTitle: { fontWeight: "900", fontSize: 15 }, cardText: { fontSize: 13, lineHeight: 19, marginTop: 4 } });
