import { api } from "./client";
const auth = (token: string) => ({ headers: { Authorization: `Bearer ${token}` } });
export type InboxConversation = { id: string; member: { id: string; anonymousUsername: string; publicAvatarUrl?: string | null; publicFlair?: string | null }; latestMessage: { text: string; createdAt: string } | null; unreadCount: number; updatedAt: string };
export type FriendshipLevel = "STRANGER" | "ACQUAINTANCE" | "FRIEND" | "CLOSE_FRIEND";
export type ConversationPrompt = { id: string; question: string; targetLevel: FriendshipLevel; targetLabel: string; status: "OFFERED" | "ACTIVE" | "COMPLETED" | "DECLINED"; waitingForConsent: boolean; myAnswer: string | null; memberAnswer: string | null; myAnswerUnavailable?: boolean; memberAnswerUnavailable?: boolean; hasAnswered: boolean; memberHasAnswered: boolean };
export type ChatConnection = { level: FriendshipLevel; levelLabel: string; nextLevel: FriendshipLevel | null; nextLevelLabel: string | null; messageCount: number; canRequestLevel: boolean; pendingLevel: FriendshipLevel | null; requestedByMe: boolean; canAcceptLevel: boolean; canOfferPrompt: boolean; prompt: ConversationPrompt | null };
export type DirectConversation = { messages: Array<{ id: string; chatId: string; senderId: string; text: string; createdAt: string; readAt?: string | null; isUnavailable?: boolean }>; otherMember: { id: string; anonymousUsername: string; publicAvatarUrl?: string | null; publicFlair?: string | null }; profileSharing: { isSharingMyProfile: boolean; canViewMemberProfile: boolean; memberId: string | null; photos: Array<{ id: string; url: string; visibility: "PRIVATE" | "PUBLIC"; createdAt: string; sharedWithMember: boolean }> }; connection: ChatConnection };
export async function getInbox(token: string) { return (await api.get("/api/conversations", auth(token))).data.conversations as InboxConversation[]; }
export async function getDirectConversation(token: string, id: string) { return (await api.get(`/api/conversations/${id}/messages`, auth(token))).data as DirectConversation; }
export async function deleteDirectConversation(token: string, id: string) { return (await api.delete(`/api/conversations/${id}`, auth(token))).data; }
export async function updateProfileSharing(token: string, id: string, share: boolean) { return (await api.patch(`/api/conversations/${id}/profile-sharing`, { share }, auth(token))).data as { success: boolean; isSharingMyProfile: boolean }; }
export async function updateChatPhotoSharing(token: string, id: string, photoId: string, share: boolean) { return (await api.patch(`/api/conversations/${id}/profile-photos/${photoId}`, { share }, auth(token))).data as { success: boolean; shared: boolean }; }
export async function updateFriendshipLevel(token: string, id: string, action: "REQUEST" | "ACCEPT") { return (await api.post(`/api/conversations/${id}/friendship-level`, { action }, auth(token))).data as { success: boolean; connection: ChatConnection }; }
export async function offerConversationPrompt(token: string, id: string) { return (await api.post(`/api/conversations/${id}/prompts`, {}, auth(token))).data as { success: boolean; prompt: ConversationPrompt }; }
export async function respondToConversationPrompt(token: string, id: string, promptId: string, action: "ACCEPT" | "DECLINE" | "ANSWER", answer?: string) { return (await api.post(`/api/conversations/${id}/prompts/${promptId}`, { action, answer }, auth(token))).data as { success: boolean; prompt: ConversationPrompt }; }
